---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "{levelname:7} | {asctime:19} | {name} | {message!r}"
        style: '{'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    verbose_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: all.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

#loggers:
#    dataprovider:
#        level: ERROR
#        handlers: [console]
#        propagate: no

root:
    level: DEBUG
    handlers: [console, verbose_file_handler, error_file_handler]
...
